[project]
name = "register_agent"
version = "0.1.0"
description = "Default template for PDM package"
authors = [{ name = "redjax", email = "jackenyon@gmail.com" }]
dependencies = [
    ## crvrs-spacetraders core module
    "httpx>=0.27.0",
    "hishel>=0.0.24",
    "core @ file:///${PROJECT_ROOT}/../../core",
]
requires-python = "==3.11.*"
readme = "README.md"
license = { text = "MIT" }


[tool.pdm]
distribution = false
